version: '3'

services:
  db_postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - viking_volume:/var/lib/postgresql/data 
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./scripts/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    networks:
      - vikingNet
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - db_postgres
    networks:
      - vikingNet

networks:
  vikingNet:

volumes:
  viking_volume:
